### ISSUE TITLE
graph-tool not available on M1 via conda

### ISSUE THREAD

**Issue by NAThompson** [conda-forge/graph-tool-feedstock#64]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

graph-tool is not available on M1.

```
$ uname -m
arm64
$ wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh
$ chmod +x Miniforge3-MacOSX-arm64.sh
$ ./Miniforge3-MacOSX-arm64.sh
$ exit # exit to get a conda base environment
(base) $ conda install graph-tool graph-tool-base
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - graph-tool-base
  - graph-tool

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/nathompson7/miniforge3:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py39h5161555_1001    conda-forge
ca-certificates           2021.5.30            h4653dfc_0    conda-forge
certifi                   2021.5.30        py39h2804cbe_0    conda-forge
cffi                      1.14.6           py39hda8b47f_0    conda-forge
chardet                   4.0.0            py39h2804cbe_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.10.3           py39h2804cbe_0    conda-forge
conda-package-handling    1.7.3            py39h5161555_0    conda-forge
cryptography              3.4.7            py39h73257c9_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
libcxx                    12.0.1               h168391b_0    conda-forge
libffi                    3.3                  h9f76cd9_2    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
openssl                   1.1.1k               h27ca646_0    conda-forge
pip                       21.2.2             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py39h5161555_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39h2804cbe_3    conda-forge
python                    3.9.6           h54d631c_1_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.80         py39h5161555_1004    conda-forge
setuptools                49.6.0           py39h2804cbe_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h72a2b83_0    conda-forge
tk                        8.6.10               hf7e6567_1    conda-forge
tqdm                      4.62.0             pyhd8ed1ab_0    conda-forge
tzdata                    2021a                he74cb21_1    conda-forge
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h642e427_0    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
(base) ➜  reproduce conda info

     active environment : base
    active env location : /Users/nathompson7/miniforge3
            shell level : 1
       user config file : /Users/nathompson7/.condarc
 populated config files : /Users/nathompson7/miniforge3/.condarc
                          /Users/nathompson7/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.6.final.0
       virtual packages : __osx=11.5.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/nathompson7/miniforge3  (writable)
      conda av data dir : /Users/nathompson7/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/nathompson7/miniforge3/pkgs
                          /Users/nathompson7/.conda/pkgs
       envs directories : /Users/nathompson7/miniforge3/envs
                          /Users/nathompson7/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.6 Darwin/20.6.0 OSX/11.5.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by stuarteberg** [comment]
We can't create an `osx-arm64` build of this feedstock until all of its dependencies have been ported first.  Fortunately, it looks like that might not take too long.  I wrote a little script to call `conda search --subdir osx-arm64 --json ${dep}` on each of graph-tool's dependencies.  As far as I can tell, only `cairomm` and its dependency `sigcpp` are currently lacking M1 support.

Just for fun, here's their relationship to `graph-tool`:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/1655821/128644435-efeb6a2e-83df-417a-9af8-7222535ea096.png">

I have no idea when to expect those last two dependencies to become available.

Since `cairomm` is only used for drawing, I suppose it would be technically feasible to provide `graph-tool-base` for M1 right now...

**Comment by stuarteberg** [comment]
FWIW, A description of the conda-forge effort to provide M1 packages can be found in [this blog post.][1]  According to those notes, a bot will automatically open a PR for our feedstock once all of the dependencies are available.  I guess we can just wait for that to happen.

[1]: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64

**Comment by NAThompson** [comment]
@stuarteberg : Thanks so much for your input! The diagram is very helpful.

**Comment by stuarteberg** [comment]
@NAThompson BTW, [conda-depgraph][1] is a handy little tool for creating such diagrams.

[1]: https://github.com/omegacen/conda-depgraph

**Comment by chrisvander** [comment]
Any updates or workarounds for this? I want to have all my packages installed via miniforge, not have graph-tool installed  through brew and then use some hacky linking.

**Comment by stuarteberg** [comment]
>Any updates or workarounds for this?

Not yet.  I think we'll need a resolution to the following question before progress can be made on `cairomm` and then `graph-tool` itself.

- https://github.com/conda-forge/libsigcpp-feedstock/issues/23

I don't know why the bots haven't automatically pushed M1 support to that feedstock.

It appears that `libsigcpp` feedstock lacks dedicated maintainers.  (The only listed maintainers are conda-forge core developers, who are probably quite busy with other things.)  If you want to prod things along, you can try asking for advice on the conda-forge gitter channel.

**Comment by stuarteberg** [comment]
The above issue with `libsigcpp` is still unresolved, so a drawing-capable M1 port is still not possible.  But now that #28 has been resolved, it should be possible to build `graph-tool-base` for the M1 package.  But I don't know how many users would actually be interested in that.

**Comment by count0** [comment]
Now that the issue above for `libsigcpp` has been fixed, what is the status on this? Is there anything else blocking `cairomm`?

**Comment by stuarteberg** [comment]
I tried to make progress via #73, but I [got stuck with an error I didn't understand][1]. Someday when I have time, I might ask for help on gitter, but this week is definitely bad for me.

[1]: https://github.com/conda-forge/graph-tool-feedstock/pull/73#issuecomment-1009152280

**Comment by tomaskourim** [comment]
> Any updates or workarounds for this? I want to have all my packages installed via miniforge, not have graph-tool installed through brew and then use some hacky linking.

@chrisvander as this is still not solved, can you please elaborate a bit more on `hacky linking`? How do you link graph-tool to conda?

**Comment by Minyall** [comment]
@tomaskourim I got a base version of graph-tool working on Apple Silicon by first installing graph-tool via [homebrew](https://formulae.brew.sh/formula/graph-tool). I then added the location of the graph-tool site-packages folder to my python path. For me the location was `/opt/homebrew/Cellar/graph-tool/2.44_1/lib/python3.9/site-packages 
`. 

I use PyCharm so this was relatively easy to add under the [interpreter preferences](https://stackoverflow.com/questions/24197970/pycharm-import-external-library). However I believe you can also do so in the script with the following.

```
import sys
sys.path.append('/opt/homebrew/Cellar/graph-tool/2.44_1/lib/python3.9/site-packages')
from graph_tool.all import *

```

It is worth noting that I found my way here because I still get runtime errors related to cairo draw and will not be able to draw graphs. This makes sense given the dependency issues discussed above.

**Comment by tomaskourim** [comment]
> @tomaskourim I got a base version of graph-tool working on Apple Silicon by first installing graph-tool via [homebrew](https://formulae.brew.sh/formula/graph-tool). I then added the location of the graph-tool site-packages folder to my python path. For me the location was `/opt/homebrew/Cellar/graph-tool/2.44_1/lib/python3.9/site-packages `.
> 
> I use PyCharm so this was relatively easy to add under the [interpreter preferences](https://stackoverflow.com/questions/24197970/pycharm-import-external-library). However I believe you can also do so in the script with the following.
> 
> ```
> import sys
> sys.path.append('/opt/homebrew/Cellar/graph-tool/2.44_1/lib/python3.9/site-packages')
> from graph_tool.all import *
> ```
> 
> It is worth noting that I found my way here because I still get runtime errors related to cairo draw and will not be able to draw graphs. This makes sense given the dependency issues discussed above.

Thanks. Adding to path did not work for me (but I can try the `sys.path.append` as well), what helped is to copy files from homebrew installation directly into the conda site-packages. Super hacky, I would say. Now I have to deal with `CBC` packages, having the same problems...

**Comment by stuarteberg** [comment]
@NAThompson @tomaskourim @Minyall

We may have a working build of `graph-tool` for M1 macs, via #73.  Before we publish it, would one of you be willing to test it?  Here's how to download the (unpublished) build artifacts:

1. Go to the [build artifacts listing for our successful build.][1]
2. Download the tarball for your platform.  (If you can't find the Download button, [check out this little video][2].)
3. Unzip the contents (twice since it's a nested zip) and install it to a conda environment:

    ```
    cd ~/Downloads
    unzip conda_artifacts_20220524.8.1_osx_arm64_numpy1.21python3.10.____cpython.zip
    cd conda_artifacts_20220524.8.1_osx_arm64_numpy1.21python3.10.____cpython
    unzip graph-tool-feedstock_conda_artifacts_20220524.8.1_osx_arm64_numpy1.21python3.10.____cpython.zip
    cd graph-tool-feedstock_conda_artifacts_20220524.8.1_osx_arm64_numpy1.21python3.10.____cpython
    conda create -n test-gt -c file://$(pwd) graph-tool-base
    conda activate test-gt
    ```
4. Try a few functions and report back here!

[1]: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=511234&view=artifacts&pathAsName=false&type=publishedArtifacts
[2]: https://imgur.com/a/4YRCTbU

**Comment by stuarteberg** [comment]
@NAThompson @tomaskourim @Minyall @chrisvander

Update: We know the artifacts I linked to in the above message are broken.  We're now rebuilding #73, so don't test anything until that is done.
